# Generated by Django 4.2.30 on 2026-09-21 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_category_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='posts', to='article.category'),
        ),
    ]
