# Generated by Django 4.2.30 on 2026-09-21 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0012_suggestions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suggestions',
            options={'ordering': ['-created_on'], 'verbose_name_plural': 'suggestions'},
        ),
    ]
